"""
Regional Policy Mapping Generator — Phase F2.

For each region:
  1. Compute the 10 metrics
  2. Derive a deterministic policy
  3. Print/export side-by-side comparison

Exports REGIONAL_POLICY_MAPPING.md.

Run:  python scripts/regional_policy_mapping_gen.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scripts.regional_intelligence_audit import load_problem_from_json
from src.decomposition.port_clustering import PortClustering
from src.decomposition.regional_splitter import RegionalSplitter
from src.agents.regional_metrics import STANDARD_REGION_NAMES
from src.agents.regional_policy_mapping import derive_all_regional_policies


def main():
    print("=" * 70)
    print("REGIONAL POLICY MAPPING — Phase F2")
    print("=" * 70)

    dataset_path = Path("data/datasets/large_shipping_problem.json")
    problem = load_problem_from_json(str(dataset_path))
    print(f"Global problem: {len(problem.ports)} ports, {len(problem.demands)} lanes")

    clusterer = PortClustering(n_clusters=5)
    clusters = clusterer.cluster_ports(problem.ports)
    splitter = RegionalSplitter(problem)
    regional_problems = splitter.split(clusters)

    sorted_clusters = sorted(clusters.keys(), key=lambda c: len(clusters[c]), reverse=True)
    name_list = list(STANDARD_REGION_NAMES.values())
    cluster_to_region = {}
    for rank, cid in enumerate(sorted_clusters):
        cluster_to_region[cid] = name_list[rank] if rank < len(name_list) else f"Region_{rank}"

    all_policies = derive_all_regional_policies(regional_problems, cluster_to_region)

    # ── Print summary table ──────────────────────────────────────────
    print("\n" + "=" * 70)
    print("DERIVED REGIONAL POLICIES")
    print("=" * 70)
    header = (
        f"{'Region':<14} {'Coverage':>9} {'Profit':>7} {'Margin':>7} "
        f"{'Vessel':>9} {'Hub#':>5} {'Corr#':>6} {'Conc':>10} {'Dens':>12}"
    )
    print(header)
    print("-" * len(header))
    for name, entry in all_policies.items():
        m = entry["metrics"]
        p = entry["policy"]
        print(
            f"{name:<14} {p['coverage_priority']:>9.2f} {p['profit_priority']:>7.2f} "
            f"{p['min_service_margin']:>7.2f} {p['vessel_bias']:>9} "
            f"{len(p['hub_focus']):>5} {len(p['corridor_focus']):>6} "
            f"{m['derived']['concentration_level']:>10} {m['derived']['density_level']:>12}"
        )

    # ── Export REGIONAL_POLICY_MAPPING.md ───────────────────────────
    output_path = Path("REGIONAL_POLICY_MAPPING.md")
    with output_path.open("w", encoding="utf-8") as f:
        f.write("# Regional Policy Mapping — Phase F2\n\n")
        f.write("**Generated by:** `scripts/regional_policy_mapping_gen.py`\n\n")
        f.write("This document defines a deterministic mapping from regional\n")
        f.write("metrics to a complete regional policy.\n\n")

        f.write("## Mapping Rules\n\n")
        f.write("### 1. Coverage & Profit Priorities (by concentration level)\n\n")
        f.write("| Concentration | Top-3 share | coverage_priority | profit_priority |\n")
        f.write("|---|---|---:|---:|\n")
        f.write("| very_high | ≥30% | 0.20 | 0.80 |\n")
        f.write("| high | 10–30% | 0.35 | 0.65 |\n")
        f.write("| moderate | 5–10% | 0.50 | 0.50 |\n")
        f.write("| low | <5% | 0.80 | 0.30 |\n\n")

        f.write("### 2. Vessel Bias (by density level)\n\n")
        f.write("| Density | lanes/(ports²/2) | vessel_bias |\n")
        f.write("|---|---|---|\n")
        f.write("| very_dense | ≥100% | large |\n")
        f.write("| dense | 60–100% | large |\n")
        f.write("| moderate | 30–60% | balanced |\n")
        f.write("| sparse | 10–30% | small |\n")
        f.write("| very_sparse | <10% | small |\n\n")

        f.write("### 3. min_service_margin (base by density + adjustments)\n\n")
        f.write("**Base:**\n\n")
        f.write("| Density | base margin |\n")
        f.write("|---|---:|\n")
        f.write("| very_dense | 0.03 |\n")
        f.write("| dense | 0.05 |\n")
        f.write("| moderate | 0.08 |\n")
        f.write("| sparse | 0.10 |\n")
        f.write("| very_sparse | 0.12 |\n\n")
        f.write("**Imbalance bonus:**\n\n")
        f.write("| Imbalance | bonus |\n")
        f.write("|---|---:|\n")
        f.write("| severe (≥40%) | +0.05 |\n")
        f.write("| moderate (20–40%) | +0.03 |\n")
        f.write("| mild (10–20%) | +0.01 |\n")
        f.write("| balanced (<10%) | +0.00 |\n\n")
        f.write("**Vessel-class adjustment:**\n\n")
        f.write("| Vessel | bonus |\n")
        f.write("|---|---:|\n")
        f.write("| large | -0.02 |\n")
        f.write("| balanced | 0.00 |\n")
        f.write("| small | +0.02 |\n")
        f.write("| feeder | +0.03 |\n\n")
        f.write("Final margin = clamp(base + imbalance_bonus + vessel_bonus, 0, 0.30)\n\n")

        f.write("### 4. Hub Focus (by hub dominance)\n\n")
        f.write("| Hub Dominance | max-hub % | hub_focus count |\n")
        f.write("|---|---|---:|\n")
        f.write("| dominant | ≥20% | 1 |\n")
        f.write("| strong | 15–20% | 2 |\n")
        f.write("| moderate | 10–15% | 3 |\n")
        f.write("| distributed | <10% | 0 |\n\n")

        f.write("### 5. Corridor Focus (by density)\n\n")
        f.write("| Density | max corridor_focus entries |\n")
        f.write("|---|---:|\n")
        f.write("| very_dense | 3 |\n")
        f.write("| dense | 5 |\n")
        f.write("| moderate | 8 |\n")
        f.write("| sparse | 10 |\n")
        f.write("| very_sparse | 3 |\n\n")
        f.write("Concentration overrides corridor count to minimum 5 when very_high/high.\n\n")

        f.write("## Derived Policies per Region\n\n")
        f.write("| Region | coverage | profit | margin | vessel | hub# | corridor# | concentration | density |\n")
        f.write("|---|---:|---:|---:|---|---:|---:|---|---|\n")
        for name, entry in all_policies.items():
            m = entry["metrics"]
            p = entry["policy"]
            f.write(
                f"| **{name}** | {p['coverage_priority']:.2f} | {p['profit_priority']:.2f} | "
                f"{p['min_service_margin']:.2f} | {p['vessel_bias']} | "
                f"{len(p['hub_focus'])} | {len(p['corridor_focus'])} | "
                f"{m['derived']['concentration_level']} | {m['derived']['density_level']} |\n"
            )

        f.write("\n## Rationale per Region\n\n")
        for name, entry in all_policies.items():
            p = entry["policy"]
            f.write(f"### {name}\n\n")
            for r in p["rationale"]:
                f.write(f"- {r}\n")
            f.write(f"\n**Hub focus:** {p['hub_focus']}\n\n")
            f.write(f"**Corridor focus:** {p['corridor_focus']}\n\n")

        # Uniqueness verification
        f.write("## Differentiation Verification\n\n")
        # Compare each pair
        names = list(all_policies.keys())
        pairs_different = 0
        total_pairs = 0
        for i in range(len(names)):
            for j in range(i + 1, len(names)):
                pi = all_policies[names[i]]["policy"]
                pj = all_policies[names[j]]["policy"]
                total_pairs += 1
                if (
                    pi["coverage_priority"]  != pj["coverage_priority"] or
                    pi["profit_priority"]    != pj["profit_priority"] or
                    pi["min_service_margin"] != pj["min_service_margin"] or
                    pi["vessel_bias"]        != pj["vessel_bias"]
                ):
                    pairs_different += 1
        f.write(f"- Region pairs compared: **{total_pairs}**\n")
        f.write(f"- Pairs with at least one differing field: **{pairs_different}**\n\n")
        f.write("**Pairwise distance matrix** (Euclidean over cov, prof, margin):\n\n")
        f.write("| | " + " | ".join(names) + " |\n")
        f.write("|---|" + "|".join(["---:"] * len(names)) + "|\n")
        for i, n1 in enumerate(names):
            p1 = all_policies[n1]["policy"]
            row = [n1]
            for j, n2 in enumerate(names):
                p2 = all_policies[n2]["policy"]
                d = (
                    (p1["coverage_priority"]  - p2["coverage_priority"])  ** 2 +
                    (p1["profit_priority"]    - p2["profit_priority"])    ** 2 +
                    (p1["min_service_margin"] - p2["min_service_margin"]) ** 2
                ) ** 0.5
                row.append(f"{d:.3f}")
            f.write("| " + " | ".join(row) + " |\n")

    print(f"\n[OK] Policy mapping exported to: {output_path}")
    print(f"   Distinct regional policies: {pairs_different} / {total_pairs} pairs differ")


if __name__ == "__main__":
    main()
