"""
Regional Intelligence Audit — Phase F1.

Loads the global problem, splits it by region, computes the 10-metric
profile for each region, and exports REGIONAL_INTELLIGENCE_AUDIT.md.

Run:  python scripts/regional_intelligence_audit.py
"""

import json
import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.optimization.data import Problem, Port, Demand, Service
from src.data.network_loader import NetworkLoader
from src.decomposition.port_clustering import PortClustering
from src.decomposition.regional_splitter import RegionalSplitter
from src.agents.regional_metrics import (
    compute_all_regions_metrics,
    STANDARD_REGION_NAMES,
)


def load_problem_from_json(path: str) -> Problem:
    """Load a Problem from a JSON dataset file (mirrors tests/test_orchestrator.py)."""
    with open(path) as f:
        data = json.load(f)
    ports = [Port(**p) for p in data["ports"]]
    services = []  # Generated later by ServiceGeneratorAgent
    demands = [Demand(**d) for d in data["demands"]]
    loader = NetworkLoader()
    distance_matrix = loader.load_distance_matrix()
    return Problem(
        ports=ports,
        services=services,
        demands=demands,
        distance_matrix=distance_matrix,
    )


def main():
    print("=" * 70)
    print("REGIONAL INTELLIGENCE AUDIT — Phase F1")
    print("=" * 70)

    # Load the global problem
    dataset_path = Path("data/datasets/large_shipping_problem.json")
    if not dataset_path.exists():
        print(f"ERROR: dataset not found: {dataset_path}")
        sys.exit(1)

    problem = load_problem_from_json(str(dataset_path))
    print(f"\nGlobal problem: {len(problem.ports)} ports, "
          f"{len(problem.demands)} lanes, {len(problem.services)} services")

    # Cluster ports into regions
    clusterer = PortClustering(n_clusters=5)
    clusters = clusterer.cluster_ports(problem.ports)
    print(f"Clustered into {len(clusters)} regions")
    for cid, pids in clusters.items():
        print(f"  Cluster {cid}: {len(pids)} ports")

    # Build regional sub-problems
    splitter = RegionalSplitter(problem)
    regional_problems = splitter.split(clusters)

    # Build cluster_id → region_name mapping based on port count order
    # (Largest cluster → Asia, etc. — same heuristic the system uses)
    sorted_clusters = sorted(clusters.keys(), key=lambda c: len(clusters[c]), reverse=True)
    name_list = list(STANDARD_REGION_NAMES.values())
    cluster_to_region = {}
    for rank, cid in enumerate(sorted_clusters):
        if rank < len(name_list):
            cluster_to_region[cid] = name_list[rank]
        else:
            cluster_to_region[cid] = f"Region_{rank}"

    # Compute metrics for all regions
    all_metrics = compute_all_regions_metrics(regional_problems, cluster_to_region)

    # ── Print summary ──────────────────────────────────────────────────
    print("\n" + "=" * 70)
    print("REGIONAL METRICS SUMMARY")
    print("=" * 70)
    header = (
        f"{'Region':<14} {'Demand':>10} {'Top3%':>7} {'Top10%':>8} "
        f"{'Med':>9} {'Avg':>9} {'Dens%':>7} {'HubC%':>7} "
        f"{'Imb%':>7} {'Vessel':>10} {'Frag':>7}"
    )
    print(header)
    print("-" * len(header))
    for name, m in all_metrics.items():
        print(
            f"{name:<14} {m['total_demand']:>10,.0f} {m['top3_corridor_share']:>7.1f} "
            f"{m['top10_concentration']:>8.1f} {m['median_lane_volume']:>9,.0f} "
            f"{m['avg_lane_volume']:>9,.0f} {m['network_density']:>7.1f} "
            f"{m['hub_centrality']:>7.1f} {m['import_export_imbalance']:>7.1f} "
            f"{m['dominant_vessel_requirement']:>10} {m['service_fragmentation']:>7.3f}"
        )

    # ── Export to REGIONAL_INTELLIGENCE_AUDIT.md ───────────────────────
    output_path = Path("REGIONAL_INTELLIGENCE_AUDIT.md")
    with output_path.open("w", encoding="utf-8") as f:
        f.write("# Regional Intelligence Audit — Phase F1\n\n")
        f.write("**Generated by:** `scripts/regional_intelligence_audit.py`\n\n")
        f.write("This audit computes 10 regional characteristics that will drive\n")
        f.write("deterministic policy differentiation in Phase F2–F3.\n\n")
        f.write("## Methodology\n\n")
        f.write("For each region the audit computes:\n\n")
        f.write("1. **Total demand** — total weekly TEU in the region\n")
        f.write("2. **Top-10 concentration** — share of demand in top-10 lanes (%)\n")
        f.write("3. **Top-3 corridor share** — share of demand in top-3 corridors (%)\n")
        f.write("4. **Median lane volume** — median TEU per lane\n")
        f.write("5. **Average lane volume** — average TEU per lane\n")
        f.write("6. **Network density** — lanes / (ports × (ports−1) / 2) (%)\n")
        f.write("7. **Hub centrality** — top-hub dominance: max hub score / total\n")
        f.write("8. **Import/export imbalance** — |outgoing − incoming| / total (%)\n")
        f.write("9. **Dominant vessel requirement** — feeder / small / balanced / large\n")
        f.write("10. **Service fragmentation** — avg ports per service / lane count\n\n")
        f.write("## Per-Region Profiles\n\n")
        f.write("| Region | Total Demand | Top-3 % | Top-10 % | Median | Avg | "
                "Density % | Hub Cent. % | Imb. % | Vessel | Frag |\n")
        f.write("|---|---:|---:|---:|---:|---:|---:|---:|---:|---|---:|\n")
        for name, m in all_metrics.items():
            f.write(
                f"| **{name}** | {m['total_demand']:,.0f} | "
                f"{m['top3_corridor_share']:.1f} | {m['top10_concentration']:.1f} | "
                f"{m['median_lane_volume']:,.0f} | {m['avg_lane_volume']:,.0f} | "
                f"{m['network_density']:.1f} | {m['hub_centrality']:.1f} | "
                f"{m['import_export_imbalance']:.1f} | "
                f"{m['dominant_vessel_requirement']} | {m['service_fragmentation']:.3f} |\n"
            )

        f.write("\n## Derived Categorical Labels\n\n")
        f.write("| Region | Concentration | Density | Imbalance | Vessel Class |\n")
        f.write("|---|---|---|---|---|\n")
        for name, m in all_metrics.items():
            d = m["derived"]
            f.write(
                f"| **{name}** | {d['concentration_level']} | "
                f"{d['density_level']} | {d['imbalance_level']} | {d['vessel_class']} |\n"
            )

        f.write("\n## Interpretation Notes\n\n")
        f.write("### Concentration Level\n")
        f.write("- `very_high` (≥50%): top-3 corridors dominate — corridor-focus strategy required\n")
        f.write("- `high` (30–50%): hub-and-spoke advantageous\n")
        f.write("- `moderate` (15–30%): mixed hub + direct\n")
        f.write("- `low` (<15%): broad coverage needed\n\n")
        f.write("### Density Level\n")
        f.write("- `dense` (≥50%): nearly all port pairs active — direct service bias\n")
        f.write("- `moderate` (20–50%): hybrid routing\n")
        f.write("- `sparse` (5–20%): consolidation via hubs\n")
        f.write("- `very_sparse` (<5%): feeder services required\n\n")
        f.write("### Imbalance Level\n")
        f.write("- `severe` (≥40%): one-way flows dominate — dedicated round-trip economics matter\n")
        f.write("- `moderate` (20–40%): directional bias affects vessel scheduling\n")
        f.write("- `mild` (10–20%): near-symmetric flows\n")
        f.write("- `balanced` (<10%): symmetric — flexible deployment\n\n")
        f.write("## Differentiability Verdict\n\n")
        # Check whether regions are actually different
        cat_signatures = []
        for name, m in all_metrics.items():
            d = m["derived"]
            sig = (
                d["concentration_level"],
                d["density_level"],
                d["imbalance_level"],
                d["vessel_class"],
            )
            cat_signatures.append((name, sig))
        unique = {s for _, s in cat_signatures}
        f.write(f"- Distinct categorical signatures: **{len(unique)} / {len(cat_signatures)}**\n\n")
        for name, sig in cat_signatures:
            f.write(f"  - **{name}**: {sig}\n")

    print(f"\n[OK] Audit exported to: {output_path}")
    print(f"   Distinct regional profiles: {len(unique)} / {len(cat_signatures)}")


if __name__ == "__main__":
    main()
